stages:
  - build
  - image

apacheds-build:
  stage: build
  image: maven:3.2.5-jdk-8
  script: build/build.sh
  cache:
    key: apacheds-$CI_BUILD_REF
    policy: push
    paths:
      - directory-server/installers/target/installers/
  variables:
    DIRECTORY_SERVER_REVISION: 2.0.0-M24

apacheds-image:
  stage: image
  services:
    - name: docker:dind
      alias: docker
  script:
    - ls -al directory-server/installers/target/installers/
    - build/image.sh
  cache:
    key: apacheds-$CI_BUILD_REF
    policy: pull
    paths:
      - directory-server/installers/target/installers/
