stages:
  - build
  - image

build:apacheds:
  stage: build
  image: maven:3.2.5-jdk-8
  script: build/build.sh
  artifacts:
    paths:
      - directory-server/installers/target/installers/*-amd64.deb
    expire_in: 1 week
  variables:
    DIRECTORY_SERVER_REVISION: 2.0.0-M24

image:apacheds:
  stage: image
  services:
    - name: docker:dind
      alias: docker
  script:
    - ls -al directory-server/installers/target/installers/
    - build/image.sh
  dependencies:
    - build:apacheds
